### ISSUE TITLE
ModuleNotFoundError: No module named 'torchE'

### ISSUE THREAD

**Issue by weiwei11** [dingmyu/CamNet#2]
Sorry, I meet a problem when I run train.sh in preTrain dir. The problem reports as follow:
```
Traceback (most recent call last):
  File "train.py", line 18, in <module>
    from torchE.D import dist_init, average_gradients, DistModule
ModuleNotFoundError: No module named 'torchE'
```

**Comment by FancyChen085** [comment]
> Sorry, I meet a problem when I run train.sh in preTrain dir. The problem reports as follow:
> 
> ```
> Traceback (most recent call last):
>   File "train.py", line 18, in <module>
>     from torchE.D import dist_init, average_gradients, DistModule
> ModuleNotFoundError: No module named 'torchE'
> ```

Hello,I have met the same problem as yours,have you solved it?
